model_name: amp
ignore:
  field_paths:
    - CreateWorkspaceInput.ClientToken
    - CreateRuleGroupsNamespaceInput.ClientToken
    - CreateRuleGroupsNamespaceInput.WorkspaceId
    - DeleteRuleGroupsNamespaceInput.WorkspaceId
  resource_names:
    - AlertManagerDefinition
resources:
  Workspace:
    fields:
      PrometheusEndpoint:
        is_read_only: true
        from:
          operation: DescribeWorkspace
          path: Workspace.PrometheusEndpoint
    exceptions:
      errors:
        404:
          code: ResourceNotFoundException
