---
apiVersion: iam.aws.crossplane.io/v1beta1
kind: IAMAccessKey
metadata:
  name: test-accesskey
spec:
  forProvider:
    userNameRef:
      name: someuser
  providerConfigRef:
    name: example
  writeConnectionSecretToRef:
    name: access-key-secret
    namespace: default
