---
apiVersion: iam.aws.crossplane.io/v1beta1
kind: IAMGroupPolicyAttachment
metadata:
  name: sample-grouppolicyattachment
spec:
  forProvider:
    policyArnRef:
      name: somepolicy
    groupNameRef:
      name: somegroup
  providerConfigRef:
    name: example
