# This YAML has not been tested manually.
apiVersion: apigatewayv2.aws.crossplane.io/v1alpha1
kind: DomainName
metadata:
  name: test-domainname
  annotations:
    # You can use this domain that is created by examples/route53.
    crossplane.io/external-name: "dev.crossplane.io"
spec:
  forProvider:
    region: us-east-1
    domainNameConfigurations:
       # Chage this to the ARN of the certificate created by examples/acm.
    -  certificateARN: arn:aws:acm:us-east-1:609897127049:certificate/6260abcb-f4c1-4fe2-8542-f360aaacf19b
  providerConfigRef:
    name: example