ignore:
  resource_names:
    - ClusterV2
    - VpcConnection
  field_paths:
    - CreateClusterInput.BrokerNodeGroupInfo
    - CreateClusterInput.ConfigurationInfo
    - CreateConfigurationInput.Name
    - CreateConfigurationInput.ServerProperties
resources:
  Configuration:
    exceptions:
      errors:
        404:
          code: BadRequestException
  Cluster:
    exceptions:
      errors:
        404:
          code: NotFoundException
