resources:
  "Distribution":
    api_versions:
    - name: "v1alpha1"
      storage: true
ignore:
  resource_names:
    - FieldLevelEncryptionProfile
    - Invalidation
    - KeyGroup
    - OriginRequestPolicy
    - PublicKey
    - StreamingDistribution
    - RealtimeLogConfig
    - MonitoringSubscription
    - FieldLevelEncryptionConfig
  field_paths:
    - DistributionConfig.CallerReference
    - Origins.Quantity
    - OriginAccessIdentityConfig.CallerReference
