---
apiVersion: eks.aws.crossplane.io/v1beta1
kind: Cluster
metadata:
  name: sample-cluster
  labels:
    example: "true"
spec:
  forProvider:
    region: us-east-1
    roleArnRef:
      name: somerole
    resourcesVpcConfig:
      publicAccessCidrs:                                                                                                                                                                                    
      - 0.0.0.0/0
      endpointPublicAccess: true
      subnetIdRefs:
        - name: sample-subnet1
        - name: sample-subnet2
    version: "1.16"
  writeConnectionSecretToRef:
    name: cluster-conn
    namespace: default
  providerConfigRef:
    name: example
