apiVersion: eks.aws.crossplane.io/v1alpha1
kind: NodeGroup
metadata:
  name: my-group
  labels:
    example: "true"
spec:
  forProvider:
    region: us-east-1
    clusterNameRef:
      name: sample-cluster
    subnetRefs:
      - name: sample-subnet1
      - name: sample-subnet2
    nodeRoleRef:
      name: somenoderole
  providerConfigRef:
    name: example
