apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: test-bucket1236123412367
  annotations:
    crossplane.io/external-name: test-bucket1236123412367
spec:
  deletionPolicy: Orphan
  forProvider:
    acl: private
    locationConstraint: us-east-2
    accelerateConfiguration:
      status: Enabled
    versioningConfiguration:
      status: Enabled
    tagging:
      tagSet:
        - key: key1
          value: val1
        - key: secondKey
          value: val2
        - key: key3
          value: val3
    objectLockEnabledForBucket: false
    lifecycleConfiguration:
      rules:
        - status: Enabled
          filter:
            prefix: "ola/"
          expiration:
            days: 15
  providerConfigRef:
    name: example